# Generated by Django 3.1.7 on 2021-03-21 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=2000)),
                ('date', models.DateTimeField(verbose_name='date published')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
